import type { Metadata } from "next";
import { DemoChat } from "@/components/DemoChat";
import { PageHeader } from "@/components/ui";

export const metadata: Metadata = {
  title: "KobeLLM",
  description: "A live, streaming chat with a self-hosted open-source LLM served by a minimal inference engine.",
};

export default function DemoPage() {
  return (
    <div className="max-w-2xl">
      <PageHeader eyebrow="~/kobellm" title="Live LLM Demo" />
      <p className="mt-4 text-muted">
        Welcome to KobeLLM! This is a live AI chat interface with a self-hosted
        open-source LLM served by LLama.cpp (now),  but will be ran on my hand 
        written miniature-inference-engine (in progress) in future! Tokens stream over SSE.
      </p>

      <div className="mt-8">
        <DemoChat />
      </div>

      <p className="mt-4 text-xs text-muted">
        Disclaimer: responses are generated by an open-source language model and may be
        inaccurate. Conversations are rate-limited and not stored. Do not enter sensitive
        information.
      </p>
    </div>
  );
}
