import type { Metadata } from "next";
import { DemoChat } from "@/components/DemoChat";
import { GatewayLiveStats } from "@/components/GatewayLiveStats";
import { PageHeader } from "@/components/ui";

export const metadata: Metadata = {
  title: "Gateway Chat",
  description:
    "A second live chat, routed through ts-llm-gateway — a production-style multi-provider LLM proxy — to AWS Bedrock, with rate limiting, failover, a circuit breaker, and caching.",
};

const SPECS = [
  { label: "Routing", value: "AWS Bedrock" },
  { label: "Failover", value: "OpenAI" },
  { label: "Policies", value: "rate-limit · retry · breaker · cache" },
  { label: "Transport", value: "SSE · cancellable" },
];

const SUGGESTIONS = [
  "Explain a circuit breaker like I'm a backend dev.",
  "Write a haiku about exponential backoff.",
  "Ask the same thing twice — show me the cache hit.",
  "What's the difference between rate limiting and load shedding?",
];

export default function GatewayPage() {
  return (
    <div className="max-w-2xl">
      <PageHeader eyebrow="~/gateway" title="Gateway Chat: a production LLM proxy, routed to AWS Bedrock" />
      <p className="mt-4 text-muted">
        This is the same click-to-stream chat as KobeLLM, but every message is routed through{" "}
        <a
          href="https://github.com/young-kobe/ts-llm-gateway"
          target="_blank"
          rel="noopener"
          className="text-accent hover:underline"
        >
          ts-llm-gateway
        </a>{" "}
        — a multi-provider LLM gateway in strict TypeScript — to AWS Bedrock (with OpenAI as
        automatic failover). Behind the stream sit real production policies: per-key/IP rate
        limiting, retry with backoff, a circuit breaker that quarantines a downed provider, and
        an LRU response cache. It&apos;s the same class of system I built at work — a real-time
        streaming pipeline — re-expressed as an LLM proxy. Your browser only ever talks to my Go
        backend, which holds the gateway key; the counters below are the gateway&apos;s own live{" "}
        <code className="font-mono text-sm">/stats</code>, proxied through that backend.
      </p>

      <div className="mt-6 flex flex-wrap gap-3">
        <a
          href="https://ts-llm-gateway.vercel.app/"
          target="_blank"
          rel="noopener"
          className="rounded-md border border-border px-3 py-1.5 text-sm font-medium transition-colors hover:border-accent hover:text-accent"
        >
          Gateway dashboard
        </a>
        <a
          href="https://github.com/young-kobe/ts-llm-gateway"
          target="_blank"
          rel="noopener"
          className="rounded-md border border-border px-3 py-1.5 text-sm font-medium transition-colors hover:border-accent hover:text-accent"
        >
          Source on GitHub
        </a>
      </div>

      <div className="mt-8">
        <DemoChat
          endpoint="/gateway"
          healthPath="/gateway/health"
          footerNote="Streaming · via ts-llm-gateway"
          startBlurb="A live chat routed through ts-llm-gateway → AWS Bedrock."
          specs={SPECS}
          suggestions={SUGGESTIONS}
        />
      </div>

      <div className="mt-8">
        <GatewayLiveStats />
      </div>

      <p className="mt-4 text-xs text-muted">
        Disclaimer: responses are generated by a third-party foundation model via AWS Bedrock and
        may be inaccurate. Conversations are rate-limited, cost-capped, and not stored. Do not
        enter sensitive information.
      </p>
    </div>
  );
}
